apiVersion: v1
kind: Service
metadata:
  name: smartassist-ai-service
  namespace: smart-frontened
  labels:
    app: smartassist-ai-app
spec:
  selector:
    app: smartassist-ai-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: smartassist-ai-external
  namespace: smart-frontened
  labels:
    app: smartassist-ai-app
spec:
  selector:
    app: smartassist-ai-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort

